language: java
jdk:
    - oraclejdk8

env:
    - secure: "vjmakn7sFVHbLFwVMz505A1vO/5+14AZMBBE+a6N7Pm664Ob/Km9Zos0STWnnA7CJ1WTjPnNHS1n6rd0NBW+m94BEky/32GAVPEm08az+XxBsWekjKM/hAUVQre56NPBs5QhyovRMVP8Re03viisA1bPFoHKm5AzvbagxvIJv3QZwMeAntKFPkCmLiw0cdhuRJNjaurnrK2Z1LHxj5WC31tvhoXWhcw/zbIRA2XoSE0moR41FJRnzzjzpBPLluQ7Lvbxp301SjkZpNBLhG/c8oLHbQ/3Asf2frGPnc4EKH4R4spckBVkNbuFYZFBE07nK4+V4idVkVC819t+qd7VLp8x2S5yhvaIkFVsVvVUmaW8BX0i/OR1mx/hkIrbkuEBP8osdmXtih4KLUFYuGRwUi0lbTiAGZNs6VaSEjzTHADCNqE2cu6YkwghgiIocjieT9/yqMSnjD4Rebcns3UR2H+Sc2JghPFtakjoiAPSgPitpTOsZo5fUrgHWBV0X0Otb4UDw4dzZyjOVcAqUD30yVXjbaCjdIVi8DTlFO7qTMXUWSYF5erdCJu9DvjjUB2htwJDnNl5xVcLLpdtFlEcyTrg4GjdrZMXQI5f3ryY95bqzNdv8tKs/ywFvA0FH8c+9WrqdW+bPlHxRVssLRHp4MbqEY5D9VMitT6T6gl/0hU="

after_success:
    - mvn -DrepoToken=$COVERALLS_TOKEN clean test jacoco:report coveralls:report
