language: java
jdk:
    - oraclejdk8

env:
    # COVERALLS_TOKEN
    - secure: "vjmakn7sFVHbLFwVMz505A1vO/5+14AZMBBE+a6N7Pm664Ob/Km9Zos0STWnnA7CJ1WTjPnNHS1n6rd0NBW+m94BEky/32GAVPEm08az+XxBsWekjKM/hAUVQre56NPBs5QhyovRMVP8Re03viisA1bPFoHKm5AzvbagxvIJv3QZwMeAntKFPkCmLiw0cdhuRJNjaurnrK2Z1LHxj5WC31tvhoXWhcw/zbIRA2XoSE0moR41FJRnzzjzpBPLluQ7Lvbxp301SjkZpNBLhG/c8oLHbQ/3Asf2frGPnc4EKH4R4spckBVkNbuFYZFBE07nK4+V4idVkVC819t+qd7VLp8x2S5yhvaIkFVsVvVUmaW8BX0i/OR1mx/hkIrbkuEBP8osdmXtih4KLUFYuGRwUi0lbTiAGZNs6VaSEjzTHADCNqE2cu6YkwghgiIocjieT9/yqMSnjD4Rebcns3UR2H+Sc2JghPFtakjoiAPSgPitpTOsZo5fUrgHWBV0X0Otb4UDw4dzZyjOVcAqUD30yVXjbaCjdIVi8DTlFO7qTMXUWSYF5erdCJu9DvjjUB2htwJDnNl5xVcLLpdtFlEcyTrg4GjdrZMXQI5f3ryY95bqzNdv8tKs/ywFvA0FH8c+9WrqdW+bPlHxRVssLRHp4MbqEY5D9VMitT6T6gl/0hU="
    # SONARCLOUD_TOKEN
    - secure: "djbGzBN7Jcfeq0QU9jN/Pb21aPNseTGbU3KcGEhgGXjYroopkS/v3G6W8kx33gfm4CCNkuEpPbABNjp1DZBklcIIz3/jEjyXjgKzsrOxP8A8/BbXO6YiT/wLJPRelr9J5HKQkH89A1meJxnKS7yv7ZgPoFjer1VbfZELp3Kj/kOBr9ZWhthiL0Z/ztjDnHX1QmHCNeFjGxV+jc9KiLqPJs/3iPRZ1HWeD5sA/2G5dbhnLQPD5pZwjsmd23DTeICQpDzuVJDuUti9qh5c+n2P2dbtpil+94uSdkHbVNPmfiik+pWSuvkC4mfuxlvQCx+/A10Wh7Cw+NKHnQUu62zZ8K5HmSVM/gmZtkl1TU8EoxX0/YEK3eDZQ0KFSrc2vRjXfNazT2J7RLKOjxmVQMjt15mvPuS2TwZ4TU8rtplXZZ96xz4egnqwp3grLtfcMgkoNZu9jHeuEtlTREgXInHm0+ozxnZq1AzMhph1Ge0pF+9Huz0DyqxdZtNu2BfvSPNJX8PndNWyfiz6YI5hB++xyv3VObt/NeAeQaxGYdXerbnSjg7bQ2HcUB2Z3uoRePFZj/nHwk/V/S7Y4Ecic0PAFynXjFYp+ATPLOiRdkzP601UiQdX0xFJ83c3S3LdFMNoM9MN7LFSx+3ygnuWODBwwnL3j5K5fKZd/uwawRUp92k="

script:
    - mvn package

after_success:
    - mvn -DrepoToken=$COVERALLS_TOKEN clean test jacoco:report coveralls:report
    - mvn -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tamada-github -Dsonar.login=${SONARCLOUD_TOKEN} sonar:sonar
    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
