language: java
jdk:
    - oraclejdk8

env:
  secure: "XGY1j+VRsRHQ5KSNR/C9GyEb0xJreydVvS6XLg9cg8qHCcnS42Hlb7UqIQZVDKp8RWpkoZiBvsuVO0I1lUYLjnzJIvnesC5vizMj69B6iHndo4Qa2Ejh/3BCPcfBBSRD+xGEFmo58T2maNb9YQA5RVZ8UA4sOSfPeSjw5Fl0RG6oQIQbco68aKgD3pCMm13sAejpTrUBWrMtCy46mHjN5qMU63mXOozs8E0tASheYjtyYHV1puDIw0BfSe+bQT3jz9jqDHMEAklHvbv3pCKvoBaBqWuUChNqIFq2RdjDuLFf38eiFaZgNaYykD15yQJo80WqHPA/Z99Pyoaql6rOmrbP2rDIF3XQ6xQHc11NcjePddLtQI/15UbS/yzsvcDgKr50ArAa08oSX3aMu4GfwLAgDNv8xAZVO0AHhVz8C9TXO9y4QIU8qoReqvJoQXQqdB9UtmLQTRJpK72KUWKXbV7N4QGgNUOzx22Ek5mjpy78kphHksz/ChlN8eeHUdaJCPf0Reyj1etfB7Yuf7gnMHCvC4allOVRycp0CXXhtZUgkxwggRsY1DC6nKTR5WEjR6c6cMm4DjdfyC12QLTCryKfjOQmC/29LkGfOjgZNaLFOsliAGH6uTn2JjVoD22qmr0gpKIBYQ5D68j6ZCKJX1eTo1sZaAso6/rScmWxY6c="

after_success:
    - mvn -DrepoToken=$COVERALLS_TOKEN clean test jacoco:report coveralls:report